### ISSUE TITLE
Getting GitHub Version Control working.

### ISSUE THREAD

**Issue by KZwick** [KZwick/MHA#3]

**Comment by KZwick** [comment]
Got GitHub and AS working togeather on my Machine. Used a very long Passphrase.
Found out you can just change the passphrase. 
https://help.github.com/articles/working-with-ssh-key-passphrases/

Will get Taki up and running tomorrow.
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

**Comment by KZwick** [comment]
Updated my Passphrase. It can be Empty or at-least 5 characters.

**Comment by KZwick** [comment]
We both are now set up with version control in the mobapp repository.

**Comment by takip12** [comment]
With version control set up, I will make changes to a separate "test" project file, copy successful code into "mobapp" which will be committed and pushed.
