### ISSUE TITLE
Clean Up Main Menu

### ISSUE THREAD

**Issue by takip12** [KZwick/MHA#4]
Create a main menu grid that is modern and user friendly with nicely spaced buttons.

**Comment by takip12** [comment]
I have made a grid layout consisting of nine buttons in my test project file.  We may not need all nine buttons but they are available and sizing may be altered as need be.

The next step will be connectivity which should be fairly simple considering my interfaces connect with no problem in my basic main menu layout.

**Comment by KZwick** [comment]
Added the email of the current user to the right top of the page.
Also made the email clickable. It brings up the sign in pages.
The current user is also set onResume.
