### ISSUE TITLE
Number of Days in a Month and Leap Year

### ISSUE THREAD

**Issue by takip12** [KZwick/MHA#6]
Considering different months have a different number of days and we use pull down menus that allow a user to specify a month, date and year for prescription refills, I need to ensure the selected month has the correct amount of selectable days.  For example, September has 30 days while October has 31 days.

I hope to cover this issue for leap years as well.

**Comment by KZwick** [comment]
Does not Java or Html have a built in Date function like that you we used back in Web I, That took care of the days in each month in the built in date spinner. We used it the forms part of Web I, AS should have the same type of thing I would think.

**Comment by takip12** [comment]
I believe Mohd had showed us how to hard code a date for a countdown or to use the system time to display the current date.  

Regardless, I am looking into using DatePicker.  I will update once I have made some progress.

**Comment by takip12** [comment]
Solved using DatePicker.

Just need to fix the month (July is the seventh month, not sixth)

![date1](https://user-images.githubusercontent.com/35202919/38167825-b35de8c8-34f1-11e8-8e67-8fcc0431e9eb.PNG)
![date2](https://user-images.githubusercontent.com/35202919/38167827-b684ccba-34f1-11e8-99c8-a21928eafafc.PNG)
