### ISSUE TITLE
Layout and Button Functionality

### ISSUE THREAD

**Issue by takip12** [KZwick/MHA#7]
Rearrange and organize layout in a manner that is user friendly and visually pleasing.  Ensure all buttons are fully functional.

Attached are screen captures of the temporary layout before altering.
![loginold](https://user-images.githubusercontent.com/35202919/38166464-20cb9a5e-34d9-11e8-9fd7-20c6519d6b8e.PNG)
![medinfoold](https://user-images.githubusercontent.com/35202919/38166465-2463c826-34d9-11e8-9690-f3349c322844.PNG)
![medtrackerold](https://user-images.githubusercontent.com/35202919/38166466-2614c954-34d9-11e8-82e3-ae895bc8bfc0.PNG)
![menuold](https://user-images.githubusercontent.com/35202919/38166467-27e6c020-34d9-11e8-806e-0be1a797570e.PNG)
![moodevalold](https://user-images.githubusercontent.com/35202919/38166470-2970000a-34d9-11e8-8c61-98818664bd27.PNG)
![proinfoold](https://user-images.githubusercontent.com/35202919/38166471-2ad9eef6-34d9-11e8-9fdb-a60bc8cb2ea4.PNG)
![userreportold](https://user-images.githubusercontent.com/35202919/38166472-2c4a9c7c-34d9-11e8-85e3-7973e09417f8.PNG)

**Comment by KZwick** [comment]
I like that shade of light blue. I seems a calm color to me.

**Comment by takip12** [comment]
I agree.  Below is the 3x3 menu grid.  I am going to replace the icons, change the colours, etc.  The red was temporary but I think using the light blue in place and keeping the bottom portion as white will look good.  I may also add on to the background design to fill it in a little more.
![capture](https://user-images.githubusercontent.com/35202919/38167105-9f1f111e-34e4-11e8-9db3-e6fa954b89a9.PNG)

**Comment by takip12** [comment]
Ignore the white text on blue, but what are your thoughts on the light blue/ivory background?
![capture](https://user-images.githubusercontent.com/35202919/38167472-1520522e-34ea-11e8-82d8-d59ce3e666ec.PNG)
